namespace Seasonality.Textures;

public static class Directories
{
    public enum PickableDirectories
    {
        None,
        Mushroom,
        MushroomYellow,
        MushroomBlue,
        JotunPuff,
        Magecap,
        Raspberry,
        Blueberry,
        Dandelion,
        Barley,
        Flax,
        Carrot,
        Turnip,
        Onion,
        CarrotSeed,
        TurnipSeed,
        OnionSeed,
        Branches,
        Flint,
        Rock,
        BoneRemains,
        SurtlingCore,
        BlackCore,
        Thistle
    }
    public enum VegDirectories
    {
        Beech,
        BeechSmall,
        Birch,
        Bushes,
        Oak,
        Pine,
        PineParticles,
        FirSmall,
        FirDead,
        FirDeadParticles,
        Fir,
        FirParticles,
        YggaShoot,
        SwampTrees,
        PlainsBush,
        Shrub,
        ShrubParticles,
        Rock,
        MeadowGrass,
        MeadowGrassShort,
        PlainsGrass,
        BlackForestGrass,
        BlackForestGrassAlt,
        SwampGrass,
        MistlandsGrass,
        PlainsFlowers,
        Ormbunke,
        Vass,
        Vines,
        WaterLilies,
        RockPlant,
        Clutter,
        CloudberryBush,
        YggdrasilSkyTree,
        None
    }
    public enum PieceDirectories
    {
        None,
        Straw,
        DarkWood,
        GoblinVillage
    }
    public enum CreatureDirectories
    {
        None,
        Gull,
        Serpent,
        Deer,
        Boar,
        Piggy,
        Neck,
        Greydwarf,
        GreydwarfShaman,
        Troll,
        Skeleton,
        Leech,
        Wraith,
        Blob,
        Oozer,
        Wolf,
        WolfCub,
        Lox,
        LoxCalf,
        Deathsquito,
        Goblin,
        GoblinBrute,
        GoblinShaman,
        Hare,
        Seeker,
        SeekerSoldier,
        SeekerBrood,
        Gjall,
        Tick,
    }
    public enum ArmorDirectories
    {
        None,
        Rags,
        Leather,
        Troll,
        Bronze,
        Iron,
        Wolf,
        Padded,
        Carapace,
        Mage
    }
}